// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAccess.proto

package grpc.SmartOffice.userAccess;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
