// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAccess.proto

package grpc.SmartOffice.userAccess;

public interface LoginStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string loginStatus = 1;</code>
   */
  java.lang.String getLoginStatus();
  /**
   * <code>string loginStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginStatusBytes();
}
