// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBox.proto

package grpc.SmartOffice.chatbox;

public interface chatStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userStatus = 1;</code>
   */
  java.lang.String getUserStatus();
  /**
   * <code>string userStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserStatusBytes();
}
