// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBox.proto

package grpc.SmartOffice.chatbox;

public final class ChatBoxServiceImpl {
  private ChatBoxServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sendChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sendChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_receiveChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_receiveChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rchatBox.proto\"6\n\017sendChatMessage\022\023\n\013se" +
      "ntMessage\030\001 \001(\t\022\016\n\006sentTo\030\002 \001(\t\"C\n\022recei" +
      "veChatMessage\022\027\n\017receivedMessage\030\001 \001(\t\022\024" +
      "\n\014receivedFrom\030\002 \001(\t\"\030\n\004user\022\020\n\010userName" +
      "\030\001 \001(\t\" \n\nchatStatus\022\022\n\nuserStatus\030\001 \001(\t" +
      "2w\n\016chatBoxService\022>\n\017GetChatMessages\022\020." +
      "sendChatMessage\032\023.receiveChatMessage\"\000(\001" +
      "0\001\022%\n\rGetChatStatus\022\005.user\032\013.chatStatus\"" +
      "\000B0\n\030grpc.SmartOffice.chatboxB\022ChatBoxSe" +
      "rviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sendChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sendChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sendChatMessage_descriptor,
        new java.lang.String[] { "SentMessage", "SentTo", });
    internal_static_receiveChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_receiveChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_receiveChatMessage_descriptor,
        new java.lang.String[] { "ReceivedMessage", "ReceivedFrom", });
    internal_static_user_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_chatStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_chatStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatStatus_descriptor,
        new java.lang.String[] { "UserStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
