// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBox.proto

package grpc.SmartOffice.chatbox;

/**
 * Protobuf type {@code ReceiveMessage}
 */
public  final class ReceiveMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReceiveMessage)
    ReceiveMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReceiveMessage.newBuilder() to construct.
  private ReceiveMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReceiveMessage() {
    receivedMessage_ = "";
    messageFrom_ = "";
    messageTime_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReceiveMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            receivedMessage_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            messageFrom_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            messageTime_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.SmartOffice.chatbox.ChatBoxServiceImpl.internal_static_ReceiveMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.SmartOffice.chatbox.ChatBoxServiceImpl.internal_static_ReceiveMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.SmartOffice.chatbox.ReceiveMessage.class, grpc.SmartOffice.chatbox.ReceiveMessage.Builder.class);
  }

  public static final int RECEIVEDMESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object receivedMessage_;
  /**
   * <code>string receivedMessage = 1;</code>
   */
  public java.lang.String getReceivedMessage() {
    java.lang.Object ref = receivedMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receivedMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string receivedMessage = 1;</code>
   */
  public com.google.protobuf.ByteString
      getReceivedMessageBytes() {
    java.lang.Object ref = receivedMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receivedMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGEFROM_FIELD_NUMBER = 2;
  private volatile java.lang.Object messageFrom_;
  /**
   * <code>string messageFrom = 2;</code>
   */
  public java.lang.String getMessageFrom() {
    java.lang.Object ref = messageFrom_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageFrom_ = s;
      return s;
    }
  }
  /**
   * <code>string messageFrom = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageFromBytes() {
    java.lang.Object ref = messageFrom_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageFrom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGETIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object messageTime_;
  /**
   * <code>string messageTime = 3;</code>
   */
  public java.lang.String getMessageTime() {
    java.lang.Object ref = messageTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageTime_ = s;
      return s;
    }
  }
  /**
   * <code>string messageTime = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageTimeBytes() {
    java.lang.Object ref = messageTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReceivedMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, receivedMessage_);
    }
    if (!getMessageFromBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messageFrom_);
    }
    if (!getMessageTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReceivedMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, receivedMessage_);
    }
    if (!getMessageFromBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messageFrom_);
    }
    if (!getMessageTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.SmartOffice.chatbox.ReceiveMessage)) {
      return super.equals(obj);
    }
    grpc.SmartOffice.chatbox.ReceiveMessage other = (grpc.SmartOffice.chatbox.ReceiveMessage) obj;

    boolean result = true;
    result = result && getReceivedMessage()
        .equals(other.getReceivedMessage());
    result = result && getMessageFrom()
        .equals(other.getMessageFrom());
    result = result && getMessageTime()
        .equals(other.getMessageTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECEIVEDMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getReceivedMessage().hashCode();
    hash = (37 * hash) + MESSAGEFROM_FIELD_NUMBER;
    hash = (53 * hash) + getMessageFrom().hashCode();
    hash = (37 * hash) + MESSAGETIME_FIELD_NUMBER;
    hash = (53 * hash) + getMessageTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.SmartOffice.chatbox.ReceiveMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.SmartOffice.chatbox.ReceiveMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.SmartOffice.chatbox.ReceiveMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ReceiveMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReceiveMessage)
      grpc.SmartOffice.chatbox.ReceiveMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.SmartOffice.chatbox.ChatBoxServiceImpl.internal_static_ReceiveMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.SmartOffice.chatbox.ChatBoxServiceImpl.internal_static_ReceiveMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.SmartOffice.chatbox.ReceiveMessage.class, grpc.SmartOffice.chatbox.ReceiveMessage.Builder.class);
    }

    // Construct using grpc.SmartOffice.chatbox.ReceiveMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      receivedMessage_ = "";

      messageFrom_ = "";

      messageTime_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.SmartOffice.chatbox.ChatBoxServiceImpl.internal_static_ReceiveMessage_descriptor;
    }

    @java.lang.Override
    public grpc.SmartOffice.chatbox.ReceiveMessage getDefaultInstanceForType() {
      return grpc.SmartOffice.chatbox.ReceiveMessage.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.SmartOffice.chatbox.ReceiveMessage build() {
      grpc.SmartOffice.chatbox.ReceiveMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.SmartOffice.chatbox.ReceiveMessage buildPartial() {
      grpc.SmartOffice.chatbox.ReceiveMessage result = new grpc.SmartOffice.chatbox.ReceiveMessage(this);
      result.receivedMessage_ = receivedMessage_;
      result.messageFrom_ = messageFrom_;
      result.messageTime_ = messageTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.SmartOffice.chatbox.ReceiveMessage) {
        return mergeFrom((grpc.SmartOffice.chatbox.ReceiveMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.SmartOffice.chatbox.ReceiveMessage other) {
      if (other == grpc.SmartOffice.chatbox.ReceiveMessage.getDefaultInstance()) return this;
      if (!other.getReceivedMessage().isEmpty()) {
        receivedMessage_ = other.receivedMessage_;
        onChanged();
      }
      if (!other.getMessageFrom().isEmpty()) {
        messageFrom_ = other.messageFrom_;
        onChanged();
      }
      if (!other.getMessageTime().isEmpty()) {
        messageTime_ = other.messageTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.SmartOffice.chatbox.ReceiveMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.SmartOffice.chatbox.ReceiveMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object receivedMessage_ = "";
    /**
     * <code>string receivedMessage = 1;</code>
     */
    public java.lang.String getReceivedMessage() {
      java.lang.Object ref = receivedMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receivedMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string receivedMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReceivedMessageBytes() {
      java.lang.Object ref = receivedMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receivedMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string receivedMessage = 1;</code>
     */
    public Builder setReceivedMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      receivedMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string receivedMessage = 1;</code>
     */
    public Builder clearReceivedMessage() {
      
      receivedMessage_ = getDefaultInstance().getReceivedMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string receivedMessage = 1;</code>
     */
    public Builder setReceivedMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      receivedMessage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object messageFrom_ = "";
    /**
     * <code>string messageFrom = 2;</code>
     */
    public java.lang.String getMessageFrom() {
      java.lang.Object ref = messageFrom_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageFrom_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string messageFrom = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageFromBytes() {
      java.lang.Object ref = messageFrom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string messageFrom = 2;</code>
     */
    public Builder setMessageFrom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageFrom_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string messageFrom = 2;</code>
     */
    public Builder clearMessageFrom() {
      
      messageFrom_ = getDefaultInstance().getMessageFrom();
      onChanged();
      return this;
    }
    /**
     * <code>string messageFrom = 2;</code>
     */
    public Builder setMessageFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageFrom_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object messageTime_ = "";
    /**
     * <code>string messageTime = 3;</code>
     */
    public java.lang.String getMessageTime() {
      java.lang.Object ref = messageTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string messageTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageTimeBytes() {
      java.lang.Object ref = messageTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string messageTime = 3;</code>
     */
    public Builder setMessageTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string messageTime = 3;</code>
     */
    public Builder clearMessageTime() {
      
      messageTime_ = getDefaultInstance().getMessageTime();
      onChanged();
      return this;
    }
    /**
     * <code>string messageTime = 3;</code>
     */
    public Builder setMessageTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageTime_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReceiveMessage)
  }

  // @@protoc_insertion_point(class_scope:ReceiveMessage)
  private static final grpc.SmartOffice.chatbox.ReceiveMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.SmartOffice.chatbox.ReceiveMessage();
  }

  public static grpc.SmartOffice.chatbox.ReceiveMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReceiveMessage>
      PARSER = new com.google.protobuf.AbstractParser<ReceiveMessage>() {
    @java.lang.Override
    public ReceiveMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReceiveMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReceiveMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReceiveMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.SmartOffice.chatbox.ReceiveMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

