// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBox.proto

package grpc.SmartOffice.chatbox;

public interface ReceiveMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReceiveMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string receivedMessage = 1;</code>
   */
  java.lang.String getReceivedMessage();
  /**
   * <code>string receivedMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getReceivedMessageBytes();

  /**
   * <code>string messageFrom = 2;</code>
   */
  java.lang.String getMessageFrom();
  /**
   * <code>string messageFrom = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageFromBytes();

  /**
   * <code>string messageTime = 3;</code>
   */
  java.lang.String getMessageTime();
  /**
   * <code>string messageTime = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageTimeBytes();
}
