// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBox.proto

package grpc.SmartOffice.chatbox;

public interface SendMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sentMessage = 1;</code>
   */
  java.lang.String getSentMessage();
  /**
   * <code>string sentMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getSentMessageBytes();

  /**
   * <code>string messageTo = 2;</code>
   */
  java.lang.String getMessageTo();
  /**
   * <code>string messageTo = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageToBytes();

  /**
   * <code>string messageTime = 3;</code>
   */
  java.lang.String getMessageTime();
  /**
   * <code>string messageTime = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageTimeBytes();
}
