// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBox.proto

package grpc.SmartOffice.chatbox;

public interface UserStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string chatStatus = 1;</code>
   */
  java.lang.String getChatStatus();
  /**
   * <code>string chatStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getChatStatusBytes();
}
