// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBox.proto

package grpc.SmartOffice.chatbox;

public interface userOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
