// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: documentRepository.proto

package grpc.SmartOffice.documentRepository;

public final class DocumentRepositoryImpl {
  private DocumentRepositoryImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestedDocument_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestedDocument_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SentDocument_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SentDocument_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewDocumentPath_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewDocumentPath_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030documentRepository.proto\"$\n\021RequestedD" +
      "ocument\022\017\n\007docName\030\001 \001(\t\"\037\n\014SentDocument" +
      "\022\017\n\007docName\030\001 \001(\t\"*\n\017NewDocumentPath\022\027\n\017" +
      "newDocumentPath\030\001 \001(\t2\211\001\n\022documentReposi" +
      "tory\022@\n\020retrieveDocument\022\022.RequestedDocu" +
      "ment\032\022.RequestedDocument\"\000(\0010\001\0221\n\014sendDo" +
      "cument\022\r.SentDocument\032\020.NewDocumentPath(" +
      "\001B?\n#grpc.SmartOffice.documentRepository" +
      "B\026DocumentRepositoryImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestedDocument_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestedDocument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestedDocument_descriptor,
        new java.lang.String[] { "DocName", });
    internal_static_SentDocument_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SentDocument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SentDocument_descriptor,
        new java.lang.String[] { "DocName", });
    internal_static_NewDocumentPath_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_NewDocumentPath_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewDocumentPath_descriptor,
        new java.lang.String[] { "NewDocumentPath", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
