// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: documentRepository.proto

package grpc.SmartOffice.documentRepository;

public interface FolderListingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FolderListing)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string folderListing = 1;</code>
   */
  java.lang.String getFolderListing();
  /**
   * <code>string folderListing = 1;</code>
   */
  com.google.protobuf.ByteString
      getFolderListingBytes();
}
