// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: documentRepository.proto

package grpc.SmartOffice.documentRepository;

public interface FolderContentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FolderContents)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filesList = 1;</code>
   */
  java.lang.String getFilesList();
  /**
   * <code>string filesList = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilesListBytes();
}
