// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: documentRepository.proto

package grpc.SmartOffice.documentRepository;

public interface NewDocumentPathOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NewDocumentPath)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string newDocumentPath = 1;</code>
   */
  java.lang.String getNewDocumentPath();
  /**
   * <code>string newDocumentPath = 1;</code>
   */
  com.google.protobuf.ByteString
      getNewDocumentPathBytes();
}
