// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: documentRepository.proto

package grpc.SmartOffice.documentRepository;

public interface SentDocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SentDocument)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string docName = 1;</code>
   */
  java.lang.String getDocName();
  /**
   * <code>string docName = 1;</code>
   */
  com.google.protobuf.ByteString
      getDocNameBytes();
}
