// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: officeInventory.proto

package grpc.SmartOffice.officeInventory;

public interface OrderStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderStatus = 1;</code>
   */
  java.lang.String getOrderStatus();
  /**
   * <code>string orderStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderStatusBytes();
}
