// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: officeInventory.proto

package grpc.SmartOffice.officeInventory;

public interface OrderedItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderedItems)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item = 1;</code>
   */
  java.lang.String getItem();
  /**
   * <code>string item = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemBytes();

  /**
   * <code>int32 count = 2;</code>
   */
  int getCount();
}
