// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBot.proto

package grpc.SmartOffice.chatbots;

public final class ChatBotServiceImpl {
  private ChatBotServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReceiveChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReceiveChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rchatBot.proto\"\007\n\005Empty\"&\n\017SendChatMess" +
      "age\022\023\n\013sentMessage\030\001 \001(\t\"-\n\022ReceiveChatM" +
      "essage\022\027\n\017receivedMessage\030\001 \001(\t2E\n\016chatB" +
      "otService\0223\n\004chat\022\020.SendChatMessage\032\023.Re" +
      "ceiveChatMessage\"\000(\0010\001B1\n\031grpc.SmartOffi" +
      "ce.chatbotsB\022ChatBotServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_SendChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SendChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendChatMessage_descriptor,
        new java.lang.String[] { "SentMessage", });
    internal_static_ReceiveChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReceiveChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReceiveChatMessage_descriptor,
        new java.lang.String[] { "ReceivedMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
