// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBox.proto

package grpc.SmartOffice.chatbots;

public final class ChatBoxServiceImpl {
  private ChatBoxServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReceiveChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReceiveChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rchatBox.proto\"6\n\017SendChatMessage\022\023\n\013se" +
      "ntMessage\030\001 \001(\t\022\016\n\006sentTo\030\002 \001(\t\"C\n\022Recei" +
      "veChatMessage\022\027\n\017receivedMessage\030\001 \001(\t\022\024" +
      "\n\014receivedFrom\030\002 \001(\t\"!\n\nChatStatus\022\023\n\013se" +
      "ntMessage\030\001 \001(\t2r\n\016chatBoxService\0223\n\004Cha" +
      "t\022\020.SendChatMessage\032\023.ReceiveChatMessage" +
      "\"\000(\0010\001\022+\n\rGetChatStatus\022\013.ChatStatus\032\013.C" +
      "hatStatus\"\000B1\n\031grpc.SmartOffice.chatbots" +
      "B\022ChatBoxServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SendChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SendChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendChatMessage_descriptor,
        new java.lang.String[] { "SentMessage", "SentTo", });
    internal_static_ReceiveChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReceiveChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReceiveChatMessage_descriptor,
        new java.lang.String[] { "ReceivedMessage", "ReceivedFrom", });
    internal_static_ChatStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ChatStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatStatus_descriptor,
        new java.lang.String[] { "SentMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
