// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBox.proto

package grpc.SmartOffice.chatbots;

public interface ChatStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sentMessage = 1;</code>
   */
  java.lang.String getSentMessage();
  /**
   * <code>string sentMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getSentMessageBytes();
}
