// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatBot.proto

package grpc.SmartOffice.chatbots;

public interface ReceiveChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReceiveChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string receivedMessage = 1;</code>
   */
  java.lang.String getReceivedMessage();
  /**
   * <code>string receivedMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getReceivedMessageBytes();

  /**
   * <code>string receivedFrom = 2;</code>
   */
  java.lang.String getReceivedFrom();
  /**
   * <code>string receivedFrom = 2;</code>
   */
  com.google.protobuf.ByteString
      getReceivedFromBytes();
}
