// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomAccess.proto

package grpc.SmartOffice.roomAccess;

public interface BoookedByOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoookedBy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomBookedBy = 1;</code>
   */
  java.lang.String getRoomBookedBy();
  /**
   * <code>string roomBookedBy = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomBookedByBytes();
}
