// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomAccess.proto

package grpc.SmartOffice.roomAccess;

public interface RoomStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomStatus = 1;</code>
   */
  java.lang.String getRoomStatus();
  /**
   * <code>string roomStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomStatusBytes();
}
