// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomAccess.proto

package grpc.SmartOffice.roomAccess;

public interface RoomBookedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomBooked)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomBookedBy = 1;</code>
   */
  java.lang.String getRoomBookedBy();
  /**
   * <code>string roomBookedBy = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomBookedByBytes();

  /**
   * <code>string bookedFor = 2;</code>
   */
  java.lang.String getBookedFor();
  /**
   * <code>string bookedFor = 2;</code>
   */
  com.google.protobuf.ByteString
      getBookedForBytes();

  /**
   * <code>string bookedOn = 3;</code>
   */
  java.lang.String getBookedOn();
  /**
   * <code>string bookedOn = 3;</code>
   */
  com.google.protobuf.ByteString
      getBookedOnBytes();
}
