// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomAccess.proto

package grpc.SmartOffice.roomAccess;

public interface RoomAvailableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomAvailable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomNo = 1;</code>
   */
  int getRoomNo();
}
