// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomAccess.proto

package grpc.SmartOffice.roomAccess;

public interface RoomBookingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomBooking)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomNo = 1;</code>
   */
  int getRoomNo();
}
